#!/bin/bash
set -e

CMD="docker run --rm $1"

function check_command {
	echo -n "Checking command $1 ... "
	($CMD $1 $2 >/dev/null 2>&1 && echo "OK") \
	|| (echo "MISSING" && exit -1)
}

check_command php --version
check_command git --version
check_command 'git flow' version
check_command 'git lfs' version

check_command ssh -V
check_command mysql --version

check_command composer --version
check_command /usr/local/bin/composer_v1.phar --version
check_command "phpenmod mbstring iconv; /usr/local/bin/composer_v2.phar --version"

