include: _tools/gitlab/*/*.yml
stages: 
  - level_1
  - level_2
  - level_3
  - level_4
  - level_5

default:
  image: nfqlt/aws-docker-tools
  tags: [nfq]
  before_script:
    - echo "docker.nfq.lt 172.18.1.171"
    - docker login $dockerhub_user $dockerhub_token
    - docker login https://docker.nfq.lt $nfqhub_user $nfqhub_token