
mysql57-data:
  stage: level_2
  needs: ["mysql57"]
  when: manual

postgres12-data:
  stage: level_2
  needs: ["postgres12"]
  when: manual

mysql56-data:
  stage: level_2
  needs: ["mysql56"]
  when: manual

solr36:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

elasticsearch22:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

rabbitmq335:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

nginx16:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

graylog20:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

sphinxsearch:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

redis2817:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

mongo24:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

apache24-fastcgi:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

php56-cli:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

memcached1421:
  stage: level_2
  needs: ["debian-jessie"]
  when: manual

chromedriver:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

toolbox-bullseye:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

elasticsearch75:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

nodeserver16:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

elasticsearch72:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

elasticsearch68:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

php82-cli:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

php81-cli:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

php71-cli:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

nginx118:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

php80-cli:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

nodeserver19:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

memcached169:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

nodeserver12:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

php73-cli:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

apache2452-fastcgi:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

docker18ce:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

rabbitmq310:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

nodeserver10:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

elasticsearch710:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

elasticsearch716:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

redis60:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

phantomjs21:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

rabbitmq389:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

nodeserver18:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

dev:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

elasticsearch79:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

mailhog:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

rabbitmq38:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

php74-cli:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

mongo50:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

apache24:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

rabbitmq378:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

aws-mock:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

nodeserver14:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

elasticsearch77:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

toolbox:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

php72-cli:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

phantomjs19:
  stage: level_2
  needs: ["debian-bullseye"]
  when: manual

mysql55-data:
  stage: level_2
  needs: ["mysql55"]
  when: manual

mysql80-data:
  stage: level_2
  needs: ["mysql80"]
  when: manual

mongo32:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

redis326:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

birt45:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

chromedriver73:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

rabbitmq366:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

memcached1433:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

nginx110:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

gearman:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

php70-cli:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

varnish50:
  stage: level_2
  needs: ["debian-stretch"]
  when: manual

certbot:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

router:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

varnish61:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

nginx114:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

redis503:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

memcached156:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

gitsync:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

toolbox-buster:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

nodeserver8:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

chromedriver83:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

elasticsearch56:
  stage: level_2
  needs: ["debian-buster"]
  when: manual

apache2438-fastcgi:
  stage: level_2
  needs: ["debian-buster"]
  when: manual
