#!/bin/bash
#set -e

CMD="docker run $1"
EXIT_CODE=0

function check_command {
	echo -n "Checking command $1 ... "
	{ $CMD $1 $2 >/dev/null 2>&1 && echo "OK"; } \
	|| { echo "MISSING" && EXIT_CODE='-1'; }
}


check_command 'postgres' --version


exit $EXIT_CODE

