#!/bin/bash
set -e

CMD="docker run --rm $1"

function check_command {
	echo -n "Checking command $1 ... "
	($CMD $1 $2 >/dev/null 2>&1 && echo "OK") \
	|| (echo "MISSING" && exit -1)
}

function check_executable {
    echo -n "Checking executable $1 ... "
    ($CMD  bash -c "type $1" >/dev/null 2>&1 && echo "OK") \
    || (echo "MISSING" && exit -1)
}

check_command sqlite3 --version
check_command psql --version
check_executable mdb-sql
check_command mysql --version
check_command mongosh --version
