
elasticsearch22-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch22-data && make all'
  needs: ["elasticsearch22"]
  when: manual

mongo24-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd mongo24-data && make all'
  needs: ["nfqlt"]
  when: manual

php56-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php56-supervisor && make all'
  needs: ["php56-cli"]
  when: manual

php56-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php56-dev && make all'
  needs: ["php56-cli"]
  when: manual

php56-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php56-fpm && make all'
  needs: ["php56-cli"]
  when: manual

php56-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php56-cron && make all'
  needs: ["php56-cli"]
  when: manual

node10:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node10 && make all'
  needs: ["toolbox-bullseye"]
  when: manual

node18:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node18 && make all'
  needs: ["toolbox-bullseye"]
  when: manual

node14:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node14 && make all'
  needs: ["toolbox-bullseye"]
  when: manual

node16:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node16 && make all'
  needs: ["toolbox-bullseye"]
  when: manual

wkhtmltopdf126-broken:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd wkhtmltopdf126-broken && make all'
  needs: ["toolbox-bullseye"]
  when: manual

db-tools:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd db-tools && make all'
  needs: ["toolbox-bullseye"]
  when: manual

node12:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node12 && make all'
  needs: ["toolbox-bullseye"]
  when: manual

wkhtmltopdf126:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd wkhtmltopdf126 && make all'
  needs: ["toolbox-bullseye"]
  when: manual

aws-tools:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd aws-tools && make all'
  needs: ["toolbox-bullseye"]
  when: manual

node19:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node19 && make all'
  needs: ["toolbox-bullseye"]
  when: manual

elasticsearch75-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch75-data && make all'
  needs: ["elasticsearch75"]
  when: manual

elasticsearch72-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch72-data && make all'
  needs: ["elasticsearch72"]
  when: manual

elasticsearch68-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch68-data && make all'
  needs: ["elasticsearch68"]
  when: manual

php82-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php82-supervisor && make all'
  needs: ["php82-cli"]
  when: manual

php82-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php82-fpm && make all'
  needs: ["php82-cli"]
  when: manual

php82-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php82-dev && make all'
  needs: ["php82-cli"]
  when: manual

php81-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php81-cron && make all'
  needs: ["php81-cli"]
  when: manual

php81-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php81-supervisor && make all'
  needs: ["php81-cli"]
  when: manual

php82-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php82-cron && make all'
  needs: ["php81-cli"]
  when: manual

php81-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php81-dev && make all'
  needs: ["php81-cli"]
  when: manual

php81-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php81-fpm && make all'
  needs: ["php81-cli"]
  when: manual

php71-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php71-cron && make all'
  needs: ["php71-cli"]
  when: manual

php71-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php71-fpm && make all'
  needs: ["php71-cli"]
  when: manual

php71-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php71-dev && make all'
  needs: ["php71-cli"]
  when: manual

php71-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php71-supervisor && make all'
  needs: ["php71-cli"]
  when: manual

php80-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php80-supervisor && make all'
  needs: ["php80-cli"]
  when: manual

php80-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php80-cron && make all'
  needs: ["php80-cli"]
  when: manual

php80-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php80-dev && make all'
  needs: ["php80-cli"]
  when: manual

php80-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php80-fpm && make all'
  needs: ["php80-cli"]
  when: manual

php73-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php73-cron && make all'
  needs: ["php73-cli"]
  when: manual

php73-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php73-dev && make all'
  needs: ["php73-cli"]
  when: manual

php73-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php73-fpm && make all'
  needs: ["php73-cli"]
  when: manual

php73-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php73-supervisor && make all'
  needs: ["php73-cli"]
  when: manual

linker18ce:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd linker18ce && make all'
  needs: ["docker18ce"]
  when: manual

elasticsearch710-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch710-data && make all'
  needs: ["elasticsearch710"]
  when: manual

elasticsearch716-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch716-data && make all'
  needs: ["elasticsearch716"]
  when: manual

elasticsearch79-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch79-data && make all'
  needs: ["elasticsearch79"]
  when: manual

php74-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php74-cron && make all'
  needs: ["php74-cli"]
  when: manual

php74-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php74-supervisor && make all'
  needs: ["php74-cli"]
  when: manual

php74-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php74-dev && make all'
  needs: ["php74-cli"]
  when: manual

php74-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php74-fpm && make all'
  needs: ["php74-cli"]
  when: manual

mongo50-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd mongo50-data && make all'
  needs: ["nfqlt"]
  when: manual

elasticsearch77-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch77-data && make all'
  needs: ["elasticsearch77"]
  when: manual

wkhtmltopdf-broken:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd wkhtmltopdf-broken && make all'
  needs: ["toolbox"]
  when: manual

wkhtmltopdf:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd wkhtmltopdf && make all'
  needs: ["toolbox"]
  when: manual

thrift091:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd thrift091 && make all'
  needs: ["toolbox"]
  when: manual

php72-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php72-cron && make all'
  needs: ["php72-cli"]
  when: manual

php72-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php72-dev && make all'
  needs: ["php72-cli"]
  when: manual

php72-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php72-supervisor && make all'
  needs: ["php72-cli"]
  when: manual

php72-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php72-fpm && make all'
  needs: ["php72-cli"]
  when: manual

mongo32-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd mongo32-data && make all'
  needs: ["nfqlt"]
  when: manual

php70-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php70-dev && make all'
  needs: ["php70-cli"]
  when: manual

phpmyadmin:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd phpmyadmin && make all'
  needs: ["php70-cli"]
  when: manual

php70-cron:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php70-cron && make all'
  needs: ["php70-cli"]
  when: manual

php70-supervisor:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php70-supervisor && make all'
  needs: ["php70-cli"]
  when: manual

php70-fpm:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd php70-fpm && make all'
  needs: ["php70-cli"]
  when: manual

mobile-proxy:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd mobile-proxy && make all'
  needs: ["nginx114"]
  when: manual

https-dev:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd https-dev && make all'
  needs: ["nginx114"]
  when: manual

proxy:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd proxy && make all'
  needs: ["nginx114"]
  when: manual

elasticsearch-tools:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch-tools && make all'
  needs: ["nginx114"]
  when: manual

thrift093:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd thrift093 && make all'
  needs: ["toolbox-buster"]
  when: manual

ffmpeg:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd ffmpeg && make all'
  needs: ["toolbox-buster"]
  when: manual

graphic-tools:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd graphic-tools && make all'
  needs: ["toolbox-buster"]
  when: manual

pdftk:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd pdftk && make all'
  needs: ["toolbox-buster"]
  when: manual

chromium:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd chromium && make all'
  needs: ["toolbox-buster"]
  when: manual

node6:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node6 && make all'
  needs: ["toolbox-buster"]
  when: manual

packager:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd packager && make all'
  needs: ["toolbox-buster"]
  when: manual

fontforge:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd fontforge && make all'
  needs: ["toolbox-buster"]
  when: manual

wkhtmltopdf125:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd wkhtmltopdf125 && make all'
  needs: ["toolbox-buster"]
  when: manual

thrift0110:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd thrift0110 && make all'
  needs: ["toolbox-buster"]
  when: manual

sonar-scanner-cli4:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd sonar-scanner-cli4 && make all'
  needs: ["toolbox-buster"]
  when: manual

node4:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node4 && make all'
  needs: ["toolbox-buster"]
  when: manual

wkhtmltopdf125-broken:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd wkhtmltopdf125-broken && make all'
  needs: ["toolbox-buster"]
  when: manual

ruby2:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd ruby2 && make all'
  needs: ["toolbox-buster"]
  when: manual

phyaml:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd phyaml && make all'
  needs: ["toolbox-buster"]
  when: manual

node8:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd node8 && make all'
  needs: ["toolbox-buster"]
  when: manual

ghostscript:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd ghostscript && make all'
  needs: ["toolbox-buster"]
  when: manual

elasticsearch56-data:
  image: nfqlt/aws-tools-docker
  tags: [nfq_ip]
  script: 'cd elasticsearch56-data && make all'
  needs: ["elasticsearch56"]
  when: manual
