
elasticsearch22-data:
  stage: level_3
  needs: ["elasticsearch22"]
  when: manual

mongo24-data:
  stage: level_3
  needs: ["mongo24"]
  when: manual

php56-supervisor:
  stage: level_3
  needs: ["php56-cli"]
  when: manual

php56-dev:
  stage: level_3
  needs: ["php56-cli"]
  when: manual

php56-fpm:
  stage: level_3
  needs: ["php56-cli"]
  when: manual

php56-cron:
  stage: level_3
  needs: ["php56-cli"]
  when: manual

node10:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

node18:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

node14:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

node16:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

wkhtmltopdf126-broken:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

db-tools:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

node12:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

wkhtmltopdf126:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

aws-tools:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

node19:
  stage: level_3
  needs: ["toolbox-bullseye"]
  when: manual

elasticsearch75-data:
  stage: level_3
  needs: ["elasticsearch75"]
  when: manual

elasticsearch72-data:
  stage: level_3
  needs: ["elasticsearch72"]
  when: manual

elasticsearch68-data:
  stage: level_3
  needs: ["elasticsearch68"]
  when: manual

php82-supervisor:
  stage: level_3
  needs: ["php82-cli"]
  when: manual

php82-fpm:
  stage: level_3
  needs: ["php82-cli"]
  when: manual

php82-dev:
  stage: level_3
  needs: ["php82-cli"]
  when: manual

php81-cron:
  stage: level_3
  needs: ["php81-cli"]
  when: manual

php81-supervisor:
  stage: level_3
  needs: ["php81-cli"]
  when: manual

php82-cron:
  stage: level_3
  needs: ["php81-cli"]
  when: manual

php81-dev:
  stage: level_3
  needs: ["php81-cli"]
  when: manual

php81-fpm:
  stage: level_3
  needs: ["php81-cli"]
  when: manual

php71-cron:
  stage: level_3
  needs: ["php71-cli"]
  when: manual

php71-fpm:
  stage: level_3
  needs: ["php71-cli"]
  when: manual

php71-dev:
  stage: level_3
  needs: ["php71-cli"]
  when: manual

php71-supervisor:
  stage: level_3
  needs: ["php71-cli"]
  when: manual

php80-supervisor:
  stage: level_3
  needs: ["php80-cli"]
  when: manual

php80-cron:
  stage: level_3
  needs: ["php80-cli"]
  when: manual

php80-dev:
  stage: level_3
  needs: ["php80-cli"]
  when: manual

php80-fpm:
  stage: level_3
  needs: ["php80-cli"]
  when: manual

php73-cron:
  stage: level_3
  needs: ["php73-cli"]
  when: manual

php73-dev:
  stage: level_3
  needs: ["php73-cli"]
  when: manual

php73-fpm:
  stage: level_3
  needs: ["php73-cli"]
  when: manual

php73-supervisor:
  stage: level_3
  needs: ["php73-cli"]
  when: manual

linker18ce:
  stage: level_3
  needs: ["docker18ce"]
  when: manual

elasticsearch710-data:
  stage: level_3
  needs: ["elasticsearch710"]
  when: manual

elasticsearch716-data:
  stage: level_3
  needs: ["elasticsearch716"]
  when: manual

elasticsearch79-data:
  stage: level_3
  needs: ["elasticsearch79"]
  when: manual

php74-cron:
  stage: level_3
  needs: ["php74-cli"]
  when: manual

php74-supervisor:
  stage: level_3
  needs: ["php74-cli"]
  when: manual

php74-dev:
  stage: level_3
  needs: ["php74-cli"]
  when: manual

php74-fpm:
  stage: level_3
  needs: ["php74-cli"]
  when: manual

mongo50-data:
  stage: level_3
  needs: ["mongo50"]
  when: manual

elasticsearch77-data:
  stage: level_3
  needs: ["elasticsearch77"]
  when: manual

wkhtmltopdf-broken:
  stage: level_3
  needs: ["toolbox"]
  when: manual

wkhtmltopdf:
  stage: level_3
  needs: ["toolbox"]
  when: manual

thrift091:
  stage: level_3
  needs: ["toolbox"]
  when: manual

php72-cron:
  stage: level_3
  needs: ["php72-cli"]
  when: manual

php72-dev:
  stage: level_3
  needs: ["php72-cli"]
  when: manual

php72-supervisor:
  stage: level_3
  needs: ["php72-cli"]
  when: manual

php72-fpm:
  stage: level_3
  needs: ["php72-cli"]
  when: manual

mongo32-data:
  stage: level_3
  needs: ["mongo32"]
  when: manual

php70-dev:
  stage: level_3
  needs: ["php70-cli"]
  when: manual

phpmyadmin:
  stage: level_3
  needs: ["php70-cli"]
  when: manual

php70-cron:
  stage: level_3
  needs: ["php70-cli"]
  when: manual

php70-supervisor:
  stage: level_3
  needs: ["php70-cli"]
  when: manual

php70-fpm:
  stage: level_3
  needs: ["php70-cli"]
  when: manual

mobile-proxy:
  stage: level_3
  needs: ["nginx114"]
  when: manual

https-dev:
  stage: level_3
  needs: ["nginx114"]
  when: manual

proxy:
  stage: level_3
  needs: ["nginx114"]
  when: manual

elasticsearch-tools:
  stage: level_3
  needs: ["nginx114"]
  when: manual

thrift093:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

ffmpeg:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

graphic-tools:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

pdftk:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

chromium:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

node6:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

packager:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

fontforge:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

wkhtmltopdf125:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

thrift0110:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

sonar-scanner-cli4:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

node4:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

wkhtmltopdf125-broken:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

ruby2:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

phyaml:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

node8:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

ghostscript:
  stage: level_3
  needs: ["toolbox-buster"]
  when: manual

elasticsearch56-data:
  stage: level_3
  needs: ["elasticsearch56"]
  when: manual
