#!/bin/bash

CMD="docker run -it -e NFQ_ENABLE_ELASTIC_MODULES $1 run-parts /etc/rc.d"


# test enabling hq module
export NFQ_ENABLE_ELASTIC_MODULES='hq'
$CMD | grep -i 'Enabling plugin.*hq' &> /dev/null \
|| (echo "Container did not reported enabling hq elastic module" && exit -1)

# test enabling head module
export NFQ_ENABLE_ELASTIC_MODULES='head'
$CMD | grep -i 'Enabling plugin.*head' &> /dev/null \
|| (echo "Container did not reported enabling head elastic module" && exit -1)

# test enabling analysis-icu module
export NFQ_ENABLE_ELASTIC_MODULES='analysis-icu'
$CMD | grep -i 'Enabling plugin.*analysis-icu' &> /dev/null \
|| (echo "Container did not reported enabling analysis-icu elastic module" && exit -1)

# test enabling kopf module
export NFQ_ENABLE_ELASTIC_MODULES='kopf'
$CMD | grep -i 'Enabling plugin.*kopf' &> /dev/null \
|| (echo "Container did not reported enabling kopf elastic module" && exit -1)


