#!/bin/bash
set -e

CMD="docker run --rm $1"
EXIT_CODE=0

function check_command {
	echo -n "Checking command $1 ... "
	{ $CMD $1 $2 >/dev/null 2>&1 && echo "OK"; } \
	|| { echo "MISSING" && EXIT_CODE='-1'; }
}


check_command 'bzip2' -h
check_command 'dig' -h
check_command 'less' --version
check_command 'nc' -h
check_command 'socat' -h
check_command 'patch' --help
#check_command 'telnet' '?'
check_command 'ping' -V
check_command 'time' --version
check_command 'traceroute' --version
check_command 'w3m' -h
check_command 'curl' --version
check_command 'wget' --version
check_command 'whiptail' --version
check_command 'ps' --version
#check_command 'netstat' --version

check_command 'vim' --version
check_command 'nethogs' -V
check_command 'pv' --version
check_command 'git' --version
check_command 'rsync' --version
check_command 'iotop' --version
check_command 'iostat' -V
check_command 'ngrep' -V
check_command 'mc' --help
check_command 'sudo' -V
check_command 'man' --version
check_command 'unzip' --help
check_command 'strace' -h
check_command 'shellcheck' --version

check_command 'getfacl' --version

check_command 'cowsay' version


exit $EXIT_CODE

