#!/bin/bash
set -e

# Script level settings
cwd=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
yml="${cwd}/docker-compose.yml"
image="$1"
pid=${BASHPID}
hostname=$(cat $yml | phyaml -k services | head -n 1 )
cname=test${pid}_${hostname}_1

source "${cwd}/../../_tools/helpers/common.sh"

# destroy containers and remove trash
cleanup() {
	set +e
	docker-compose -p "test${pid}" -f $yml stop &>/dev/null
	docker-compose -p "test${pid}" -f $yml rm -fv &>/dev/null
	set -e
}
trap cleanup EXIT

run_test() {
	local ip="$1"
	local match="$2"
	local t1=$(date +%s)
	local t2=0
	local timeout=$3

	while true; do
		if wget --retry-connrefused --waitretry=1 -t 1 -T 5 -qO- "$ip" | grep -q "$match"; then
			return 0
		fi

		t2=$(date +%s)
		if [ $(($t2-$t1)) -ge $timeout ]; then
			return 1
		fi

		sleep 1
	done
}

docker-compose -p "test${pid}" -f $yml up -d &>/dev/null
box_ip=$(get_container_ip $cname)
wait_for_connection $box_ip:80 46

run_test  $box_ip "<h1>Home</h1>" 60

exit 0

