#!/bin/bash
set -e

CMD="docker run --rm $1"

function check_command {
	echo -n "Checking command $1 ... "
	($CMD $1 $2 >/dev/null 2>&1 && echo "OK") \
	|| (echo "MISSING" && exit -1)
}


check_command node --version
check_command npm --version
check_command gulp --version
check_command grunt --version
#check_command node-sass --version
check_command bower --version
check_command uglifycss
check_command uglifyjs --version
check_command tsc --version
check_command tslint --version
check_command ts-node --version

