
cypress7:
  stage: level_4
  needs: ["node16"]
  when: manual

cypress9:
  stage: level_4
  needs: ["node16"]
  when: manual

cypress5:
  stage: level_4
  needs: ["node12"]
  when: manual

cypress4:
  stage: level_4
  needs: ["node12"]
  when: manual

aws-docker-tools:
  stage: level_4
  needs: ["aws-tools"]
  when: manual

xhgui:
  stage: level_4
  needs: ["php81-dev"]
  when: manual

php74-vscode:
  stage: level_4
  needs: ["php74-dev"]
  when: manual

deb-dev:
  stage: level_4
  needs: ["php70-dev"]
  when: manual
