
deb-dev:
  stage: level_4
  script: 'cd deb-dev && make all && make publish'
  needs: ["php70-dev"]
  when: on_success

php74-vscode:
  stage: level_4
  script: 'cd php74-vscode && make all && make publish'
  needs: ["php74-dev"]
  when: on_success

xhgui:
  stage: level_4
  script: 'cd xhgui && make all && make publish'
  needs: ["php81-dev"]
  when: on_success

aws-docker-tools:
  stage: level_4
  script: 'cd aws-docker-tools && make all-amd64 && make publish-amd64'
  needs: [aws-docker-tools_arm64]
  when: on_success
aws-docker-tools_arm64:
  stage: level_4
  script: 'cd aws-docker-tools && make all-arm64 && make publish-arm64'
  tags: [arm]
  needs: ["aws-tools"]
  when: on_success

cypress4:
  stage: level_4
  script: 'cd cypress4 && make all && make publish'
  needs: ["node12"]
  when: on_success

cypress5:
  stage: level_4
  script: 'cd cypress5 && make all && make publish'
  needs: ["node12"]
  when: on_success

cypress7:
  stage: level_4
  script: 'cd cypress7 && make all && make publish'
  needs: ["node16"]
  when: on_success

cypress9:
  stage: level_4
  script: 'cd cypress9 && make all && make publish'
  needs: ["node16"]
  when: on_success

aws-docker-tools:
  stage: level_4
  script: 'cd aws-docker-tools && make all-amd64 && make publish-amd64'
  needs: [aws-docker-tools_arm64]
  when: on_success
aws-docker-tools_arm64:
  stage: level_4
  script: 'cd aws-docker-tools && make all-arm64 && make publish-arm64'
  tags: [arm]
  needs: ["aws-tools"]
  when: on_success

cypress4:
  stage: level_4
  script: 'cd cypress4 && make all && make publish'
  needs: ["node12"]
  when: on_success

cypress5:
  stage: level_4
  script: 'cd cypress5 && make all && make publish'
  needs: ["node12"]
  when: on_success

cypress7:
  stage: level_4
  script: 'cd cypress7 && make all && make publish'
  needs: ["node16"]
  when: on_success

cypress9:
  stage: level_4
  script: 'cd cypress9 && make all && make publish'
  needs: ["node16"]
  when: on_success
