
lib-smartclient130:
  stage: level_1
  needs: []
  when: manual

mysql57:
  stage: level_1
  needs: []
  when: manual

postgres12:
  stage: level_1
  needs: []
  when: manual

mysql56:
  stage: level_1
  needs: []
  when: manual

lib-smartclient120:
  stage: level_1
  needs: []
  when: manual

debian-jessie:
  stage: level_1
  needs: []
  when: manual

debian-bullseye:
  stage: level_1
  needs: []
  when: manual

lib-smartclient111:
  stage: level_1
  needs: []
  when: manual

mariadb10:
  stage: level_1
  needs: []
  when: manual

mysql55:
  stage: level_1
  needs: []
  when: manual

mysql80:
  stage: level_1
  needs: []
  when: manual

lib-smartclient100:
  stage: level_1
  needs: []
  when: manual

lib-smartclient121:
  stage: level_1
  needs: []
  when: manual

debian-stretch:
  stage: level_1
  needs: []
  when: manual

debian-buster:
  stage: level_1
  needs: []
  when: manual
