
postgres12:
  stage: level_1
  script: 'cd postgres12 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

mysql80:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_os docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd mysql80 && make all-amd64 && make push-manifest && make publish && make clean'
  needs: [mysql80_arm64]
  when: manual
  allow_failure: false
  tags: [nfq_ip]
mysql80_arm64:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_aws docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd mysql80 && make all-arm64 && make clean'
  tags: [arm]
  needs: []
  when: manual
  allow_failure: false

mysql57:
  stage: level_1
  script: 'cd mysql57 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

mysql56:
  stage: level_1
  script: 'cd mysql56 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

mysql55:
  stage: level_1
  script: 'cd mysql55 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

mariadb10:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_os docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd mariadb10 && make all-amd64 && make push-manifest && make publish && make clean'
  needs: [mariadb10_arm64]
  when: manual
  allow_failure: false
  tags: [nfq_ip]
mariadb10_arm64:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_aws docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd mariadb10 && make all-arm64 && make clean'
  tags: [arm]
  needs: []
  when: manual
  allow_failure: false

lib-smartclient130:
  stage: level_1
  script: 'cd lib-smartclient130 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

lib-smartclient121:
  stage: level_1
  script: 'cd lib-smartclient121 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

lib-smartclient120:
  stage: level_1
  script: 'cd lib-smartclient120 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

lib-smartclient111:
  stage: level_1
  script: 'cd lib-smartclient111 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

lib-smartclient100:
  stage: level_1
  script: 'cd lib-smartclient100 && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

dib:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_os docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd dib && make all-amd64 && make push-manifest && make publish && make clean'
  needs: [dib_arm64]
  when: manual
  allow_failure: false
  tags: [nfq_ip]
dib_arm64:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_aws docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd dib && make all-arm64 && make clean'
  tags: [arm]
  needs: []
  when: manual
  allow_failure: false

debian-stretch:
  stage: level_1
  script: 'cd debian-stretch && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

debian-buster:
  stage: level_1
  script: 'cd debian-buster && make all && make publish && make clean'
  needs: []
  when: manual
  allow_failure: false

debian-bullseye:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_os docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd debian-bullseye && make all-amd64 && make push-manifest && make publish && make clean'
  needs: [debian-bullseye_arm64]
  when: manual
  allow_failure: false
  tags: [nfq_ip]
debian-bullseye_arm64:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_aws docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd debian-bullseye && make all-arm64 && make clean'
  tags: [arm]
  needs: []
  when: manual
  allow_failure: false

debian-bookworm:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_os docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd debian-bookworm && make all-amd64 && make push-manifest && make publish && make clean'
  needs: [debian-bookworm_arm64]
  when: manual
  allow_failure: false
  tags: [nfq_ip]
debian-bookworm_arm64:
  stage: level_1
  before_script:
    # this ip has to go to host
    - echo $nfqhub_ip_aws docker.nfq.lt >> /etc/hosts
    - docker login -u $dockerhub_user -p $dockerhub_token
    - docker login -u $nfqhub_user -p $nfqhub_token https://docker.nfq.lt
  script: 'cd debian-bookworm && make all-arm64 && make clean'
  tags: [arm]
  needs: []
  when: manual
  allow_failure: false
