#!/bin/bash

CMD="docker run -it -e NFQ_ENABLE_VARNISH_MODULES $1 run-parts /etc/rc.d"


# test enabling no modules
export NFQ_ENABLE_VARNISH_MODULES=''
$CMD | grep -i 'Enabling module' &> /dev/null \
&& (echo "Container reported enabling module which it was not asked to enable" && exit -1)

# test enabling unknown modules
export NFQ_ENABLE_VARNISH_MODULES='foo bar'
$CMD | grep -i 'WARNING: module .* is not available' &> /dev/null \
|| (echo "Container did not reported unknown module" && exit -1)

# test enabling saintmode module
export NFQ_ENABLE_VARNISH_MODULES='saintmode'
$CMD | grep -i 'Enabling module.*saintmode' &> /dev/null \
|| (echo "Container did not reported enabling saintmode module" && exit -1)



