#!/bin/bash
set -ex

# prepare test
pid=$BASHPID
tmp_dir="${pwd}/${test_pid}"
echo "PACKAGIST_TOKEN='aaabbbcccddd'" > $tmp_dir

cleanup() {
        rm /tmp/test${pid}
}

docker run -v "$tmp_dir:/etc/environment-vm:ro" $1 run-parts /etc/rc.d \
| grep -i 'Adding packagist token' &> /dev/null \
|| (echo "Container did not reported appending packagist token using environment-vm file" && cleanup && exit -1)

docker run -e "PACKAGIST_TOKEN='aaabbbcccddd'" $1 run-parts /etc/rc.d \
| grep -i 'Adding packagist token' &> /dev/null \
|| (echo "Container did not reported appending packagist token using environment variable" && cleanup && exit -1)


cleanup


