#!/bin/bash
set -e

docker run "$1" bash -c "echo \"GITLAB_COM_TOKEN='aaabbbcccddd'\" >> /etc/environment-vm && run-parts /etc/rc.d" \
| grep -i 'Adding gitlab.com token' &> /dev/null \
|| (echo "Container did not reported appending gitlab token using environment-vm file" && cleanup && exit 1)

docker run -e "GITLAB_COM_TOKEN='aaabbbcccddd'" "$1" run-parts /etc/rc.d \
| grep -i 'Adding gitlab.com token' &> /dev/null \
|| (echo "Container did not reported appending gitlab token using environment variable" && cleanup && exit 1)

