#!/bin/bash
set -e

docker run -it $1 bash -c "echo \"PACKAGIST_TOKEN='aaabbbcccddd'\" >> /etc/environment-vm && run-parts /etc/rc.d" \
| grep -i 'Adding packagist token' &> /dev/null \
|| (echo "Container did not reported appending packagist token using environment-vm file" && exit -1)

docker run -e "PACKAGIST_TOKEN='aaabbbcccddd'" $1 run-parts /etc/rc.d \
| grep -i 'Adding packagist token' &> /dev/null \
|| (echo "Container did not reported appending packagist token using environment variable" && exit -1)


