#!/bin/bash
set -ex

# prepare test
pid=$BASHPID
tmp_dir="${pwd}/${test_pid}"
echo "VM_GITHUB_TOKEN='aaabbbcccddd'" > $tmp_dir

cleanup() {
	rm $tmp_dir
}

docker run -v "$tmp_dir:/etc/environment-vm:ro" $1 run-parts /etc/rc.d \
| grep -i 'Adding github token' &> /dev/null \
|| (echo "Container did not reported appending github token using environment-vm file" && cleanup && exit -1)

docker run -e "VM_GITHUB_TOKEN='aaabbbcccddd'" $1 run-parts /etc/rc.d \
| grep -i 'Adding github token' &> /dev/null \
|| (echo "Container did not reported appending github token using environment variable" && cleanup && exit -1)


cleanup
