#!/bin/bash
set -e

# prepare test
pid=$BASHPID

docker run -it $1 bash -c "echo \"VM_GITHUB_TOKEN='aaabbbcccddd'\" >> /etc/environment-vm && run-parts /etc/rc.d" \
| grep -i 'Adding github token' &> /dev/null \
|| (echo "Container did not reported appending github token using environment-vm file" && cleanup && exit -1)

docker run -it -e "VM_GITHUB_TOKEN='aaabbbcccddd'" $1 run-parts /etc/rc.d \
| grep -i 'Adding github token' &> /dev/null \
|| (echo "Container did not reported appending github token using environment variable" && cleanup && exit -1)

