#!/bin/bash

CMD="docker run -e NFQ_ENABLE_RABBITMQ_MODULES $1 run-parts /etc/rc.d"

# test enabling some modules
export NFQ_ENABLE_RABBITMQ_MODULES='rabbitmq_management'
$CMD | grep -i 'Enabling.*rabbitmq.*modules.*rabbitmq_management' &> /dev/null \
|| (echo "Container did not reported enabling selected RabbitMQ modules" && exit -1)


