#!/bin/bash
set -e

tpl=$(realpath $0).tpl
cwd=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
imageDir=$(dirname $cwd)
mysqlImage=$(cat ${imageDir}/Dockerfile | grep FROM | sed 's/FROM //')
mysqlDataImage="$1"
pid=${BASHPID}

source "${cwd}/../../_tools/helpers/common.sh"

# destroy containers and remove trash
cleanup() {
     docker-compose -p "test${pid}" -f "${cwd}/docker-compose-${pid}.yml" stop &>/dev/null
     docker-compose -p "test${pid}" -f "${cwd}/docker-compose-${pid}.yml" rm -fv &>/dev/null

     rm -f "${cwd}/docker-compose-${pid}.yml"
}

trap cleanup EXIT

# helper method to run actuall tests
testQuery() {
    mysql_ip="$1"
    user="$2"
    password="$3"
    query="$4"

    echo -n "Testing query: '$query' .... "
    if ! docker exec "test${pid}_mysql_1" bash -c "mysql -h ${mysql_ip} -u ${user} -p${password} -e \"${query}\"" >/dev/null; then
		echo "ERROR"
        exit 1
    fi

	echo "OK"
}

# start mysql server container with data volume from the tested image
cat $tpl | sed \
-e "s#__MYSQL_IMAGE__#${mysqlImage}#" \
-e "s#__MYSQL_DATA_IMAGE__#${mysqlDataImage}#" \
> "${cwd}/docker-compose-${pid}.yml"

docker-compose -p "test${pid}" -f "${cwd}/docker-compose-${pid}.yml" up -d &>/dev/null

ip_address="$(get_container_ip test${pid}_mysql_1)"
wait_for_connection "${ip_address}:3306"

# actual tests
testQuery "$ip_address" project project "use project"
testQuery "$ip_address" project project "show databases"
testQuery "$ip_address" project project "create database project_test"
testQuery "$ip_address" project project "use project_test"

