#!/bin/bash
set -e

CMD="docker run --rm $1"

function check_command {
	echo -n "Checking command $1 ... "
	($CMD $1 $2 >/dev/null 2>&1 && echo "OK") \
	|| (echo "MISSING" && exit -1)
}

function check_executable {
    echo -n "Checking executable $1 ... "
    ($CMD  bash -c "type $1" >/dev/null 2>&1 && echo "OK") \
    || (echo "MISSING" && exit -1)
}

check_command aws --version
check_command eb --version
check_command ebp --version
check_command docker --version
check_command az --version
check_command kubectl "version --client"


